import { Montserrat } from 'next/font/google'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import { ThemeProvider } from '@mui/material/styles'
import './globals.css'
import theme from './theme'
import { Fab } from '@mui/material'
import Footer from '@/components/Footer'
import { WhatsApp } from '@mui/icons-material'
import Header from '@/components/Header'

const inter = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <Header />
            <main>
              {children}
              <Fab
                style={{
                  position: 'fixed',
                  bottom: 16,
                  right: 16,
                }}
                variant="extended"
                color="success"
              >
                <WhatsApp
                  className="mr-2"
                  style={{ textTransform: 'none' }}
                  color="white"
                />
                WhatsApp
              </Fab>
            </main>
            <Footer />
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
