import { Inter } from 'next/font/google'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import { ThemeProvider } from '@mui/material/styles'
import './globals.css'
import theme from './theme'
import { Button } from '@mui/material'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

const menus = []

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <header className="">
              <nav className="max-w-7xl ml-auto mr-auto">
                <ul className="flex items-center justify-between p-5">
                  <li>
                    <Image alt="logo" src="/logo.svg" width={177} height={50} />
                  </li>
                  <ul className="flex items-center ">
                    <li>
                      <a href="#home">Home</a>
                    </li>
                    <li>
                      <a href="#sobre">O Grupo eQuilíbrio</a>
                    </li>
                    <li>
                      <a href="#servicos">Soluções</a>
                    </li>
                    <li>
                      <a href="#contato">Notícias & Eventos</a>
                    </li>
                    <li>
                      <Button variant="contained">Fale Conosco</Button>
                    </li>
                  </ul>
                </ul>
              </nav>
            </header>
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
